=== M-Igashi/cologne-raves/event.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "venue",
      "date",
      "title",
      "startTime"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "venue": {
        "type": "string"
      },
      "date": {
        "type": "string",
        "format": "date"
      },
      "title": {
        "type": "string"
      },
      "startTime": {
        "type": "string",
        "pattern": "^\\d{2}:\\d{2}$"
      },
      "artists": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "url": {
        "type": "string",
        "format": "uri"
      }
    },
    "additionalProperties": false
  }
}

=== M-Igashi/cologne-raves/data/2025-07-cologne-16-to-08-02.json
[
  {
    "id": "7550b070",
    "title": "Beats x Bass x Cologne w/ Sofie Sapuna #MittWochenende",
    "venue": "Odonien",
    "date": "2025-07-16",
    "startTime": "23:00",
    "artists": [
      "Sofie Sapuna",
      "Rosilicious",
      "LSG",
      "DJ Discostoff",
      "Gourski",
      "Enaly"
    ],
    "url": "https://ra.co/events/2208948"
  },
  {
    "id": "b199d3ac",
    "title": "Andhim in Odonien",
    "venue": "Odonien",
    "date": "2025-07-18",
    "startTime": "23:00",
    "artists": [
      "Andhim",
      "Rafael Da Cruz",
      "Julian Bomm",
      "Mike Momburg"
    ],
    "url": "https://ra.co/events/2189227"
  },
  {
    "id": "a2f94344",
    "title": "THICK & JUICY - KHM Rundgangsparty 2025",
    "venue": "JAKI",
    "date": "2025-07-18",
    "startTime": "23:00",
    "artists": [
      "Sedaction",
      "low Ki"
    ],
    "url": "https://ra.co/events/2211896"
  },
  {
    "id": "83c78b0a",
    "title": "Technoblock Hardtechno x Hardbounce Session",
    "venue": "Elektroküche",
    "date": "2025-07-19",
    "startTime": "23:00",
    "artists": [
      "FØSS",
      "Boltcore",
      "Faronis"
    ],
    "url": "https://ra.co/events/2202913"
  },
  {
    "id": "2b069946",
    "title": "BergWacht in Odonien with Miss Melera, Lampé uvm",
    "venue": "Odonien",
    "date": "2025-07-19",
    "startTime": "23:00",
    "artists": [
      "Miss Melera",
      "Lampé",
      "Liho"
    ],
    "url": "https://ra.co/events/2199370"
  },
  {
    "id": "322a3757",
    "title": "inner rhythm",
    "venue": "Tanzfaktur",
    "date": "2025-07-19",
    "startTime": "14:00",
    "artists": [
      "Nadim",
      "HiHat",
      "DJ Palga"
    ],
    "url": "https://ra.co/events/2196488"
  },
  {
    "id": "a1670f67",
    "title": "Tom-Tom Club feat. DJ Lu & Nadim",
    "venue": "JAKI",
    "date": "2025-07-19",
    "startTime": "23:30",
    "artists": [
      "Nadim"
    ],
    "url": "https://ra.co/events/2200041"
  },
  {
    "id": "28f77686",
    "title": "VICE BOAT CRUISE 2025 with Leon Hagen & Pascal Wagner (HOOVE)",
    "venue": "TBA - Anleger 13 - Bastei Köln (MS Rheinland)",
    "date": "2025-07-19",
    "startTime": "16:30",
    "artists": [
      "Leon Hagen",
      "Pascal Wagner"
    ],
    "url": "https://ra.co/events/2210643"
  },
  {
    "id": "bd6589b3",
    "title": "fi x Lange Nacht",
    "venue": "fi",
    "date": "2025-07-19",
    "startTime": "18:00",
    "artists": [
      "Philipp Stoffel",
      "Mike Momburg",
      "Leon Hagen",
      "Pascal Wagner"
    ],
    "url": "https://ra.co/events/2209647"
  },
  {
    "id": "6bc56a82",
    "title": "FLINTA* DJ CONTEST - GIRLS JUST WANNA HAVE FUN'",
    "venue": "H26",
    "date": "2025-07-19",
    "startTime": "22:00",
    "artists": [
      "AGNY"
    ],
    "url": "https://ra.co/events/2212560"
  },
  {
    "id": "7f6d49e0",
    "title": "Beats x Bass x Cologne #MittWochenende",
    "venue": "Odonien",
    "date": "2025-07-23",
    "startTime": "23:00",
    "artists": [],
    "url": "https://ra.co/events/2208992"
  },
  {
    "id": "f98eb2d8",
    "title": "Sommer Rave at Odonien",
    "venue": "Odonien",
    "date": "2025-07-25",
    "startTime": "23:00",
    "artists": [
      "Ankytrixx",
      "Alchemiah",
      "Kos:mo",
      "Shaun Moses",
      "Steven Shade",
      "Laura Foxx"
    ],
    "url": "https://ra.co/events/2170037"
  },
  {
    "id": "ff7f1ab5",
    "title": "Austin Millz pres by Bootshaus LIVE",
    "venue": "Bootshaus",
    "date": "2025-07-25",
    "startTime": "19:00",
    "artists": [
      "Austin Millz"
    ],
    "url": "https://ra.co/events/2195675"
  },
  {
    "id": "146ab00a",
    "title": "FOR FREE - Artheater SUMMER SPECIAL I",
    "venue": "Artheater",
    "date": "2025-07-25",
    "startTime": "23:00",
    "artists": [
      "Redfocks",
      "DJ VENUSSS"
    ],
    "url": "https://ra.co/events/2212653"
  },
  {
    "id": "70987d70",
    "title": "fi = altshift5 with Marcel Dettmann & Plasma & rau.ton",
    "venue": "fi",
    "date": "2025-07-26",
    "startTime": "23:00",
    "artists": [
      "Elisen",
      "Marcel Dettmann",
      "BORGBORG",
      "makahaun",
      "Rostøm"
    ],
    "url": "https://ra.co/events/2209588"
  },
  {
    "id": "e938f2bd",
    "title": "BZZBZZ TECHNO X RCL w/Raven",
    "venue": "Helios37",
    "date": "2025-07-26",
    "startTime": "23:00",
    "artists": [
      "Raven (CA)",
      "SPEEDO (2)",
      "KACHU2K"
    ],
    "url": "https://ra.co/events/2208076"
  },
  {
    "id": "56e2896f",
    "title": "In Limbo Audio Open Air",
    "venue": "Autonomes Zentrum",
    "date": "2025-07-26",
    "startTime": "14:00",
    "artists": [
      "AMSL",
      "Motip White",
      "Separat"
    ],
    "url": "https://ra.co/events/2211137"
  },
  {
    "id": "249426a5",
    "title": "DJ DIESEL pres. by SHAQ´S BASS ALL-STARS",
    "venue": "Bootshaus",
    "date": "2025-07-26",
    "startTime": "22:00",
    "artists": [
      "San Holo"
    ],
    "url": "https://ra.co/events/2186555"
  },
  {
    "id": "987531b4",
    "title": "HNTR PRES BY Bootshaus",
    "venue": "Bootshaus",
    "date": "2025-07-26",
    "startTime": "23:00",
    "artists": [
      "HNTR",
      "Nic Lorenz"
    ],
    "url": "https://ra.co/events/2171583"
  },
  {
    "id": "ff9d3cb2",
    "title": "Tom-Tom Club x Diana Kollektiv x Another Thought",
    "venue": "JAKI",
    "date": "2025-07-26",
    "startTime": "23:30",
    "artists": [],
    "url": "https://ra.co/events/2196577"
  },
  {
    "id": "dc791c97",
    "title": "AMAPIANO FEST - OPEN AIR EDITION",
    "venue": "TBA - MOXY COLOGNE/BONN AIRPORT",
    "date": "2025-07-27",
    "startTime": "16:00",
    "artists": [
      "DJ Freegah",
      "Cajoux"
    ],
    "url": "https://ra.co/events/2201230"
  },
  {
    "id": "be0a9510",
    "title": "Bootshaus on a Ship with Muzz, Subsonic, Aeon:Mode",
    "venue": "TBA",
    "date": "2025-07-27",
    "startTime": "14:00",
    "artists": [
      "Gourski"
    ],
    "url": "https://ra.co/events/2185978"
  },
  {
    "id": "13789217",
    "title": "Beats x Bass x Cologne #MittWochenende",
    "venue": "Odonien",
    "date": "2025-07-30",
    "startTime": "23:00",
    "artists": [],
    "url": "https://ra.co/events/2208994"
  },
  {
    "id": "d2ece4e7",
    "title": "ART OF URBAN LIFE SPECIAL - BIRTHDAY RAVE",
    "venue": "Artheater",
    "date": "2025-08-01",
    "startTime": "23:00",
    "artists": [
      "CÖLN",
      "SITTENLOS",
      "DJ SODBRENNEN"
    ],
    "url": "https://ra.co/events/2208485"
  },
  {
    "id": "0c0f0d7e",
    "title": "Techno Allianz Pres. 1 Year Schranz Only Local Night",
    "venue": "Elektroküche",
    "date": "2025-08-02",
    "startTime": "23:00",
    "artists": [
      "Ropemaker",
      "Roben Gardemann",
      "I.D.A"
    ],
    "url": "https://ra.co/events/2169254"
  },
  {
    "id": "2ac2dd1d",
    "title": "Techno Dampfer Köln with Spartaque",
    "venue": "TBA - Am Leystapel auf der Höhe des Schokoladenmuseums, Köln",
    "date": "2025-08-02",
    "startTime": "17:00",
    "artists": [
      "Spartaque"
    ],
    "url": "https://ra.co/events/2121363"
  },
  {
    "id": "95eabbc2",
    "title": "GUTE NACHT! mit Chrissyjeey und sarah4K im Helios37",
    "venue": "Helios37",
    "date": "2025-08-02",
    "startTime": "23:00",
    "artists": [
      "Bounce MC",
      "sarah4K",
      "Speedo"
    ],
    "url": "https://ra.co/events/2207876"
  },
  {
    "id": "4c7689a4",
    "title": "FOR FREE - Artheater SUMMER SPECIAL II",
    "venue": "Artheater",
    "date": "2025-08-02",
    "startTime": "23:00",
    "artists": [
      "alleira",
      "Arninho",
      "BOLZ"
    ],
    "url": "https://ra.co/events/2212656"
  }
]

=== M-Igashi/cologne-raves/data/2025-09-cologne-30-b74ccf.json
[
  {
    "id": "1d50f8b8",
    "title": "MITTWOCHENENDE feat. RAVES of GERMANY & MK RAVES",
    "venue": "Odonien",
    "date": "2025-10-01",
    "startTime": "23:00",
    "artists": [
      "Simba",
      "Super Dario",
      "Dj Danevska",
      "Dj Eddyble",
      "Dj MÃ¤sisch B2B ISSAM",
      "Dr Pheelgood",
      "Rui Da Silva",
      "Bbxngz",
      "Prayinhell",
      "Zoltec"
    ],
    "url": "https://tonite.ticket.io/8D6vdzsF/"
  }
]

=== M-Igashi/cologne-raves/data/2026-08-odonien-events.json
[
  {
    "title": "WIR Schwestern ･ New Frequencies",
    "venue": "Odonien",
    "date": "2026-08-01",
    "startTime": "23:00",
    "artists": [
      "LOLSNAKE",
      "ESZTER",
      "REDFOCKS",
      "CALI CARACHO",
      "RACHEL RAW",
      "ROMY MVP",
      "GRETA PEROLA",
      "LEYA",
      "VIBE & VIPER",
      "ENNA"
    ],
    "url": "https://rausgegangen.de/events/wir-schwestern-new-frequencies-august-rush-0/",
    "id": "9dbc2c56"
  },
  {
    "title": "Electronic Summer of Love '26 (Friday)",
    "venue": "Odonien",
    "date": "2026-08-07",
    "startTime": "23:00",
    "artists": [
      "Laura vom Jupiter",
      "LIEKS",
      "Matech",
      "NVNS",
      "Perle",
      "Chaya",
      "Isabelle Beaucamp",
      "IN FURCHT",
      "SUP"
    ],
    "url": "https://rausgegangen.de/events/electronic-summer-of-love-2026-the-odonien-festival-part-xiv-0/",
    "id": "1fc116f4"
  },
  {
    "title": "Electronic Summer of Love '26 (Saturday Day Rave)",
    "venue": "Odonien",
    "date": "2026-08-08",
    "startTime": "14:00",
    "artists": [
      "Danilo Filipe",
      "DJ Sodbrennen",
      "Jacuzi",
      "Limoncello",
      "Lola Cerise",
      "Ben Techy",
      "DJ Danevska",
      "EDNA",
      "Pipo",
      "ROWIN",
      "Bish",
      "Enaly",
      "Gourski",
      "LAETi",
      "Natty Lou",
      "Omox"
    ],
    "url": "https://rausgegangen.de/events/electronic-summer-of-love-2026-the-odonien-festival-part-xiv-0/",
    "id": "07dccb6f"
  }
]

=== M-Igashi/cologne-raves/data/2026-07-gewoelbe-events.json
[
  {
    "title": "Phonovision CSD",
    "venue": "Gewölbe",
    "date": "2026-07-04",
    "startTime": "23:00",
    "artists": [
      "Alleira & Skathi",
      "DJ Ass Tits & Various Identities",
      "DJ Fucks Himself & HiHat"
    ],
    "url": "https://gewoelbe.ticket.io/4C4Mq92X/",
    "id": "c2fb3604"
  },
  {
    "title": "Jack This",
    "venue": "Gewölbe",
    "date": "2026-07-11",
    "startTime": "23:00",
    "artists": [
      "Clara Luise",
      "Pancratio",
      "Måtyrer"
    ],
    "url": "https://gewoelbe.ticket.io/MWK2ya3V/",
    "id": "28967670"
  },
  {
    "title": "Gewölbe @Odonien",
    "venue": "Odonien",
    "date": "2026-07-31",
    "startTime": "23:00",
    "artists": [],
    "url": "https://gewoelbe.ticket.io/7CWbGZ6s/",
    "id": "7330a795"
  }
]

=== M-Igashi/cologne-raves/data/2025-12-cologne-05-658735.json
[
  {
    "id": "0b99aad3",
    "title": "PSYCHO THRILL :: 34 Years of Science Friction Techno",
    "venue": "somewhere in Cologne :D",
    "date": "2025-12-06",
    "startTime": "22:00",
    "artists": [
      "ALEC TUCKER",
      "CLAUS BACHOR",
      "DJ ALTO",
      "DRIVETRAIN",
      "DRUM:MAJOR 2525",
      "MaeshRoombOY UA",
      "MARKUS FUNKE",
      "REDMADVELVET",
      "ROLAND CASPER"
    ],
    "url": "https://www.facebook.com/events/1314256426644061/"
  }
]

=== M-Igashi/cologne-raves/data/2025-10-cologne-01-2fcf86.json
[
  {
    "id": "cbf8771b",
    "title": "High Voltage X KÃ¶ln ist Techno - prod. by MATTERMIND",
    "venue": "BOGEN 2",
    "date": "2025-10-02",
    "startTime": "23:00",
    "artists": [
      "@ambam.69",
      "@bbxngz",
      "@dana.roosy",
      "@jowijane",
      "@sofiesapuna_music"
    ],
    "url": "https://www.mattermindevents.de/highvoltage"
  }
]

=== M-Igashi/cologne-raves/data/2025-04-cologne-08-extract-2.json
[

  {
    "id": "3ca0a252",
    "venue": "Bootshaus",
    "date": "2025-05-23",
    "title": "CHROME COLOGNE W. JAZZY, OMAKS, SECRET GUEST & MORE",
    "artists": [
      "JAZZY (2)",
      "OMAKS",
      "HOEHENANGST",
      "Leonard Palm",
      "Tzaar"],
    "startTime": "23:00",
    "url": "https://bootshaus-club.ticket.io/0mckscju/?fbclid=PAZXh0bgNhZW0CMTEAAachtSEwbiVUVh3obv4o3GHh8DRx7a4JoIZYB1fjm9JIU-k5Ju8WVC9QUBBETw_aem_Fh1s1TXt239nbwpvHgMqCw"
  },

  { "venue": "Helios 37",
    "date": "2025-04-26",
    "title": "NURBÖSE – 26.04.2025 – Tag der Lesbischen Sichtbarkeit",
    "artists": [
      "Métaraph",
      "Døpair",
      "Nina Sativa",
      "Sadicca"
    ],
    "startTime": "23:00",
    "url": "https://t.rausgegangen.de/tickets/nurbose-26042025"
  },
  { "venue": "Helios 37",
    "date": "2025-05-24",
    "title": "NURBÖSE – 26.04.2025 – Tag der Lesbischen Sichtbarkeit",
    "artists": [
      "Métaraph",
      "Døpair",
      "Nina Sativa",
      "Sadicca"
    ],
    "startTime": "23:00",
    "url": "https://t.rausgegangen.de/tickets/nurbose-26042025"
  },

  { "venue": "Club Zimmermanns",
    "date": "2025-05-17",
    "title": "Kinky Techno & Friends ",
    "artists": ["Moekli",
      "Hill",
      "Gerrit X",
      "Deniz (LJ)"],
    "startTime": "22:00",
    "url": "https://www.instagram.com/p/DGDR6fANkiA/"
  }
]

=== M-Igashi/cologne-raves/data/2026-nurboese-events.json
[
  {
    "venue": "Garagen Club",
    "date": "2026-03-21",
    "title": "NURFLUID Köln",
    "startTime": "23:00",
    "artists": [
      "Nur Jaber",
      "Nana Yaa",
      "Heepmann",
      "Døpair",
      "Bouncy Bitch",
      "Selunia",
      "B!B!",
      "Zuza"
    ],
    "url": "https://nurboese.de/events/nurfluid-koeln-21-03-2026/",
    "id": "bdab9d39"
  },
  {
    "venue": "Helios37",
    "date": "2026-04-18",
    "title": "NURBÖSE Köln",
    "startTime": "23:00",
    "artists": [
      "MÉTARAPH",
      "ARES",
      "DØPAIR",
      "SØSSA"
    ],
    "url": "https://rausgegangen.de/en/events/nurbose-1804-0/?mtm_campaign=teilen_gewinnspiel&mtm_kwd=web",
    "id": "1aa040e2"
  },
  {
    "venue": "Helios37",
    "date": "2026-05-16",
    "title": "NURBÖSE Köln",
    "startTime": "23:00",
    "artists": [
      "Neon Graveyard",
      "DØPAIR",
      "Esther",
      "Sadicca b2b Maddycation"
    ],
    "url": "https://rausgegangen.de/en/events/nurbose-1605-0/?action=participate-lottery-nurbose-1605-0?mtm_campaign=teilen_gewinnspiel&mtm_kwd=web",
    "id": "9cd25a16"
  },
  {
    "venue": "Artheater",
    "date": "2026-06-13",
    "title": "NURFLUID Köln",
    "startTime": "23:00",
    "artists": [],
    "url": "https://nurboese.de/events/nurfluid-13-06/",
    "id": "af74310e"
  },
  {
    "venue": "Garagen Club",
    "date": "2026-07-04",
    "title": "NURBÖSE Open Air",
    "startTime": "13:00",
    "artists": [],
    "url": "https://rausgegangen.de/en/events/nurbose-472026-open-air-0/",
    "id": "63f239fd"
  }
]
