=== M-Igashi/cologne-raves/event.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "venue",
      "date",
      "title",
      "startTime"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "venue": {
        "type": "string"
      },
      "date": {
        "type": "string",
        "format": "date"
      },
      "title": {
        "type": "string"
      },
      "startTime": {
        "type": "string",
        "pattern": "^\\d{2}:\\d{2}$"
      },
      "artists": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "url": {
        "type": "string",
        "format": "uri"
      }
    },
    "additionalProperties": false
  }
}

=== M-Igashi/cologne-raves/data/2026-02-23-new-ra-events.json
[
  {
    "id": "12e17e2b",
    "venue": "Garagen",
    "date": "2026-02-25",
    "title": "TECHNOLiEBE #AmMittwoch",
    "artists": [],
    "startTime": "20:00",
    "url": "https://ra.co/events/2376939"
  },
  {
    "id": "295360ea",
    "venue": "Elektroküche",
    "date": "2026-02-28",
    "title": "Schranz Only w/TEKKERKANE",
    "artists": [
      "I.D.A"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2342784"
  },
  {
    "id": "4cd8ab3f",
    "venue": "Schrotty",
    "date": "2026-02-28",
    "title": "VOOV PARTY OMIKI-PHAXE-SENSIFEEL",
    "artists": [],
    "startTime": "23:00",
    "url": "https://ra.co/events/2374431"
  },
  {
    "id": "12af7a86",
    "venue": "Odonien",
    "date": "2026-03-06",
    "title": "Lichtblick- Season opening 2026 in Odonien",
    "artists": [
      "Alchemiah",
      "Brtinzz",
      "Gilles Bock",
      "Kos:mo"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2321747"
  },
  {
    "id": "06c049ed",
    "venue": "Yuca Club",
    "date": "2026-03-06",
    "title": "EERIE X LOCAL BASS  with BUKEZ FINEZT, Roklem, Sebalo & many more",
    "artists": [
      "BUKEZ FINEZT",
      "Roklem",
      "Sebalo"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2369523"
  },
  {
    "id": "4f3b4c95",
    "venue": "Schrotty",
    "date": "2026-03-06",
    "title": "BZZBZZ TECHNO X MILLIAMPERE",
    "artists": [
      "Paralich",
      "DJ HÖRDE",
      "Eurodance2000",
      "SPEEDO (2)",
      "YËDM",
      "Athina",
      "Shemm",
      "Pamela Rave",
      "HENNESY",
      "PANA (Ger)"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2360225"
  },
  {
    "id": "36a238db",
    "venue": "Artheater",
    "date": "2026-03-06",
    "title": "303 presents O.B.I. & Frederic. (All Night Long)",
    "artists": [
      "O.B.I. (DE)",
      "Frederic.",
      "LSG",
      "Lianka"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2330549"
  },
  {
    "id": "b8b831ee",
    "venue": "Garagen",
    "date": "2026-03-06",
    "title": "BEATS x BASS x WEEKENDER hosted by BLOOMCAST",
    "artists": [
      "Rosilicious",
      "Fae Morgana"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2375480"
  },
  {
    "id": "7529e9b5",
    "venue": "fi",
    "date": "2026-03-06",
    "title": "fi = altshift5 with Ellen Allien & Etage147",
    "artists": [
      "Shaleen"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2349249"
  },
  {
    "id": "862efe42",
    "venue": "Helios37",
    "date": "2026-03-06",
    "title": "akt Party",
    "artists": [
      "KLARYOKO",
      "alleira"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2361021"
  },
  {
    "id": "29732710",
    "venue": "JAKI",
    "date": "2026-03-06",
    "title": "JAKI presents: All Night Long with Nadim b2b SPECIAL GUEST",
    "artists": [
      "Nadim"
    ],
    "startTime": "23:30",
    "url": "https://ra.co/events/2373078"
  },
  {
    "id": "76c65b1b",
    "venue": "Bootshaus",
    "date": "2026-03-06",
    "title": "LUKE MADNESS ALL NIGHT LONG [360°]",
    "artists": [],
    "startTime": "23:00",
    "url": "https://ra.co/events/2361298"
  },
  {
    "id": "cfd76811",
    "venue": "Kunstwerk",
    "date": "2026-03-07",
    "title": "Øhne Bedenken x 969 - Kollektiv Nacht VOL. II",
    "artists": [
      "Kashinski",
      "PATEK!",
      "andré wiese",
      "bashii (2)",
      "Dj Bowlz"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2365892"
  },
  {
    "id": "32e5a74f",
    "venue": "Bootshaus",
    "date": "2026-03-07",
    "title": "9 YEARS NIBIRII pres. VINI VICI / POLTERGST",
    "artists": [
      "Mr.Black (UK)",
      "DELTA LABS",
      "Paranormila",
      "Rui Da Silva",
      "Enaly",
      "Gourski",
      "LYNE"
    ],
    "startTime": "22:00",
    "url": "https://ra.co/events/2344161"
  },
  {
    "id": "995e5e88",
    "venue": "Helios37",
    "date": "2026-03-07",
    "title": "240KM/H pres. International Women's Day Charity",
    "artists": [
      "Riana Holley",
      "TANJA MIJU"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2353469"
  },
  {
    "id": "00c1d33b",
    "venue": "fi",
    "date": "2026-03-07",
    "title": "fi = altshift5 with 3000 Grad & Tiefgang",
    "artists": [
      "Katzengold",
      "Mollono.Bass",
      "nøvae",
      "J.WOCKENFUSS",
      "NORO",
      "ZHTA"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2349587"
  },
  {
    "id": "c03c1a14",
    "venue": "Odonien",
    "date": "2026-03-07",
    "title": "Anti Disco with Lars Eidinger (DJ-Set)",
    "artists": [
      "Lars Eidinger"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2349148"
  },

  {
    "id": "79abee3d",
    "venue": "Artheater",
    "date": "2026-03-07",
    "title": "jedermensch. with Caniche & Samantha Togni",
    "artists": [
      "Aaro (3)",
      "Caniche",
      "Samantha Togni",
      "EPHIE"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2362506"
  },
  {
    "id": "f5dffa88",
    "venue": "Blue Shell",
    "date": "2026-03-07",
    "title": "Neon Paradise x Cassetter - Syntwave/Cyberpunk Party",
    "artists": [],
    "startTime": "23:00",
    "url": "https://ra.co/events/2349454"
  },
  {
    "id": "feb41668",
    "venue": "Subway",
    "date": "2026-03-07",
    "title": "IMMERNOCH! TANZEN",
    "artists": [],
    "startTime": "17:00",
    "url": "https://ra.co/events/2360953"
  }
]

=== M-Igashi/cologne-raves/data/2025-09-cologne-21-a5e61b.json
[
  {
    "id": "fe973136",
    "title": "Desire w/Pegassi ",
    "venue": "Schrotty",
    "date": "2025-10-02",
    "startTime": "23:00",
    "artists": [
      "Pegassi",
      "Beau Didier",
      "Kim Swim",
      "Human Safari",
      "Florian Picasso",
      "Gutkind",
      "Tschatsching"
    ],
    "url": "https://desire-world.ticket.io/Rw9gmhNZ/?utm_medium=paid&utm_source=ig&utm_id=6852456735533&utm_content=6852498116133&utm_term=6852456735733&utm_campaign=6852456735533&fbclid=PAb21jcAM9FPVleHRuA2FlbQEwAGFkaWQAAAY7evor_QGnnZxOyWJC_vO9TlcDDQR-bjnffe766tOXaYuKWZXhmm46jyXmOV0fHlqjQhk_aem_iOHf6WVJVuoYI3kxx6f75A"
  },
  {
    "id": "7f6eebb8",
    "title": "United Kinkdom",
    "venue": "Die Halle Tor 2",
    "date": "2025-10-17",
    "startTime": "21:30",
    "artists": [
      "TBD"
    ],
    "url": "https://anny.co/book/united-kinkdom-171025-die-halle-tor-2"
  },
  {
    "id": "5f04f3d5",
    "title": "Chin Chin Walhalla",
    "venue": "Club Bahnhof Ehrenfeld / YUCA",
    "date": "2025-11-29",
    "startTime": "23:00",
    "artists": [
      "Nico Held",
      "B!B!"
    ],
    "url": "https://vivenu.com/event/chin-chin-koln-walhalla-p15qb6"
  },
  {
    "id": "6ce39454",
    "title": "Unicorn Cologne women power night",
    "venue": "Klub Domhof",
    "date": "2025-10-10",
    "startTime": "22:00",
    "artists": [
      "Pardis",
      "Susi & Paula",
      "Rachel Raw",
      "Dilaval"
    ],
    "url": "https://www.holidayevents.net/unicorncologne-wpn"
  }
]

=== M-Igashi/cologne-raves/data/2025-05-cologne-25.json
[
  {
    "id": "4c791ad7",
    "title": "Unicorn Cologne invites Libidoh ",
    "venue": "Klub Domhof",
    "date": "2025-08-08",
    "startTime": "22:00",
    "artists": [
      "Nico Held",
      "Rachel Raw",
      "Bianka Banks",
      "Erebos"
    ],
    "url": "https://www.holidayevents.net/unicorncologne"
  },
  {
    "id": "60badf7d",
    "title": "Kinky Galore Köln RAW Edition",
    "venue": "Bollwerk",
    "date": "2025-06-20",
    "startTime": "22:00",
    "artists": [
      "assistyler",
      "TBA"
    ],
    "url": "https://kinkygalore.net/event/koeln-3"
  },
  {
    "id": "5bbeecf0",
    "title": "SCHWARZ",
    "venue": "DIE HALLE Tor 2",
    "date": "2025-06-21",
    "startTime": "22:00",
    "artists": [
      "SKADI",
      "Alejandro Alvarez"
    ],
    "url": "https://www.joyclub.com/en/event/1710295.schwarz_21_06_25_die_halle_tor_2_koeln.html"
  },
    {
    "id": "a413a339",
    "title": "NURBÖSE x SYMBIOTIKKA",
    "venue": "Schrotty",
    "date": "2025-06-28",
    "startTime": "23:00",
    "artists": [
      "WANTON",
      "DØPAIR",
      "STUCKEYRELLA",
      "MILLIE FORSBERG"
    ],
    "url": "https://t.rausgegangen.de/tickets/nurbose-x-symbiotikka"
  },
    {
    "id": "541b2437",
    "title": "Kinky Circus",
    "venue": "Club Bahnhof Ehrenfeld",
    "date": "2025-06-28",
    "startTime": "22:00",
    "artists": [
      "TBD"
    ],
    "url": "https://www.kinkycircus.de/tickets-koeln-cbe/"
  },
  {
    "id": "2acfa74a",
    "title": "KINKY / ONE – SIN & SINNERS",
    "venue": "Electrum Club",
    "date": "2025-06-21",
    "startTime": "22:00",
    "artists": [
      "TBD"
    ],
    "url": "https://www.kinky-one.com"
  }
]

=== M-Igashi/cologne-raves/data/2025-08-cologne-12.json
[
  {
    "id": "a736ad9d",
    "title": "Kinky/One",
    "venue": "Dillenburger Stra√üe",
    "date": "2025-09-13",
    "startTime": "22:00",
    "artists": [],
    "url": "https://www.kinky-one.com"
  },
  {
    "id": "4d15a036",
    "title": "Kinky Circus",
    "venue": "Club Bahnhof Ehrenfeld",
    "date": "2025-09-27",
    "startTime": "22:00",
    "artists": [
      "Olinski & Hotsauce",
      "Misha Frenkman & Francesca Felice",
      "Olinski & Hotsauce",
      "Miss Ellavic",
      "Donnerlotta"
    ],
    "url": "https://www.kinkycircus.de/tickets-koeln-cbe/"
  },
  {
    "id": "56675cf4",
    "title": "Bittersweet ",
    "venue": "Hidden Club, Brabanter Str. 15",
    "date": "2025-09-20",
    "startTime": "20:00",
    "artists": [
      "TOBI SMIL3 aka HalfNaked"
    ],
    "url": "https://nightevents.ticket.io/mzzynwn3/?"
  }
]

=== M-Igashi/cologne-raves/data/2025-09-cologne-05-add-events-2025-09-8e866f.json
[
  {
    "id": "23b37a6e",
    "title": "Koelnisttechno",
    "venue": "Helios37",
    "date": "2025-09-05",
    "startTime": "23:00",
    "artists": [
      "Franky-B",
      "Per Pleks",
      "DJ Werbung",
      "Edna",
      "FoxTune",
      "Patrick Schumm",
      "Super Dario"
    ],
    "url": "https://rausgegangen.de/en/events/koelnisttechno-w-per-pleks-franky-b-uvm-050925-at-helios-col-0/"
  },
  {
    "id": "03e3674f",
    "title": "Simple present with Jascha Yousefi, Sedaction, Stranger",
    "venue": "Gewölbe",
    "date": "2025-09-05",
    "startTime": "23:00",
    "artists": [
      "Jascha Yousefi",
      "Sedaction",
      "stranger"
    ],
    "url": "https://ra.co/events/2239067"
  },
  {
    "id": "fe2612a1",
    "title": "Artheater Summerclosing (For Free)",
    "venue": "Artheater",
    "date": "2025-09-05",
    "startTime": "22:30",
    "artists": [
      "Moutevelidis b2b Gutkind",
      "Eva Mo b2b Pileta",
      "Tschatsching"
    ],
    "url": "https://ra.co/events/2251885"
  },
  {
    "id": "ee18d4ab",
    "title": "fi x WINE OUT",
    "venue": "fi",
    "date": "2025-09-05",
    "startTime": "23:00",
    "artists": [
      "Giselle Soundsystem",
      "Wolfram"
    ],
    "url": "https://ra.co/events/2241798"
  },
  {
    "id": "6022dd0f",
    "venue": "Odonien",
    "date": "2025-09-10",
    "title": "Beats x Bass x Cologne #MittWochenende",
    "artists": [
      "Selunia",
      "LELO",
      "LSG"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2248366"
  },
  {
    "id": "5834c06b",
    "venue": "Nachtigall",
    "date": "2025-12-10",
    "title": "Petrified Phoenix Showcase Ehrenfeld",
    "artists": [
      "Avocado",
      "Leon Licht",
      "Rallo",
      "Kathi Liz"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2246412"
  },
  {
    "id": "d0dc071a",
    "venue": "Gewölbe",
    "date": "2025-12-10",
    "title": "HOOVE",
    "artists": [
      "Eileen",
      "Julian Feierabend",
      "Matthias (1)",
      "Pascal Wagner"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2244590"
  },
  {
    "id": "72746a60",
    "venue": "Helios37",
    "date": "2025-12-10",
    "title": "240 KM/H pres. Serafina ALL NIGHT LONG",
    "artists": [
      "Serafina",
      "Anna Konda"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2255994"
  },
  {
    "id": "b3849e9e",
    "venue": "Club Castell",
    "date": "2025-12-10",
    "title": "HYPERRAVE: FREE FIRE RAVE",
    "artists": [
      "DAESU",
      "Koelschetrance",
      "Mischverhältnis",
      "Elyante"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2251545"
  },
  {
    "id": "ae05bb8c",
    "venue": "Schrotty",
    "date": "2025-13-10",
    "title": "POLTERGST invites Moji by ARTOFURBANLIFE & ONLYRAVES",
    "artists": [
      "POLTERGST",
      "MOJI",
      "Ventris x Pixs",
      "Bishalbacht",
      "LSG"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2240025"
  },
  {
    "id": "300f3565",
    "venue": "Odonien",
    "date": "2025-13-10",
    "title": "BACK2BASICS",
    "artists": [
      "AKA AKA",
      "PAPPENHEIMER"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2245953"
  },
  {
    "id": "6d75ff21",
    "venue": "Gewölbe",
    "date": "2025-13-10",
    "title": "Remember the Future",
    "artists": [
      "Perel",
      "Shumi"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2242135"
  }
]

=== M-Igashi/cologne-raves/data/2025-05-cologne-13.json
[
  {
    "id": "640f2df2",
    "title": "fi = altshift5 w/ Red Axes & Tiefgang",
    "venue": "fi",
    "date": "2025-05-16",
    "startTime": "23:00",
    "artists": [
      "KEIKEE",
      "RED AXES",
      "ROBIN KAMP",
      "TIEFGANG w/",
      "KIRA KETE",
      "STELLSON & ŠPII",
      "TILMENSCH"
    ],
    "url": "https://www.eventbrite.com/e/fi-altshift5-w-red-axes-tiefgang-tickets-1328191268839?aff=ebdsoporgprofile&keep_tld=1"
  },
  {
    "id": "182991c7",
    "title": "fi = altshift5 w/ Estella Boersma & Schleuse Eins",
    "venue": "fi",
    "date": "2025-05-17",
    "startTime": "23:00",
    "artists": [
      "ESTELLA BOERSMA",
      "KRACKK b2b ROBIN",
      "TASI DI²",
      "SCHLEUSE EINS w/",
      "NO SERVICE",
      "SCHLEUSE EINS DJ TEAM"
    ],
    "url": "https://www.eventbrite.com/e/fi-altshift5-w-estella-boersma-schleuse-eins-tickets-1310315170949?aff=ebdsoporgprofile&keep_tld=1"
  },
  {
    "id": "6a1cf5bc",
    "title": "fi = altshift5 w/ Modeselektor & Neue Wellen",
    "venue": "fi",
    "date": "2025-05-30",
    "startTime": "23:00",
    "artists": [
      "MODESELEKTOR",
      "ETANE",
      "NEUE WELLEN w/",
      "BUBATZ & SOHN",
      "EXPO2000 (FKA DJ HENNE) -live-",
      "JOSHUA VON SÖHNEN b2b DANIEL KALLHOFF",
      "NINI PANINI",
      "ROMAN"
    ],
    "url": "https://www.eventbrite.com/e/fi-altshift5-w-modeselektor-neue-wellen-tickets-1308397615489?aff=ebdsoporgprofile&keep_tld=1"
  },
  {
    "id": "465da0e1",
    "title": "fi = altshift5 w/ Daria Kolosova & nonchalance & Komm Raven",
    "venue": "fi",
    "date": "2025-05-31",
    "startTime": "23:00",
    "artists": [
      "DARIA KOLOSOVA",
      "DJ SPORTSCHUH",
      "FLAVIUS b2b VAGABUND",
      "KOMM RAVEN",
      "ARIEL",
      "DJ SPORT",
      "JAN TROVATO b2b ESKARLATION3OOO",
      "KILSTADUNDBILSTAD"
    ],
    "url": "https://www.eventbrite.com/e/fi-altshift5-w-daria-kolosova-nonchalance-komm-raven-tickets-1345081267279?aff=ebdsoporgprofile&keep_tld=1"
  }
]

=== M-Igashi/cologne-raves/data/2025-09-cologne-16-7482f3.json
[
  {
    "id": "eac19132",
    "title": "fi = altshift5 w/ Courtesy & Dübl & Friends",
    "venue": "fi",
    "date": "2025-10-11",
    "startTime": "23:00",
    "artists": [
      "AINO",
      "COURTESY",
      "C00LM8 B2B LEMSN",
      "DÜBL",
      "JOHANNES TON",
      "MIMIZAN"
    ],
    "url": "https://www.eventbrite.com/e/fi-altshift5-w-courtesy-dubl-friends-tickets-1635085858819?aff=ebdsoporgprofile&keep_tld=1"
  }
]

=== M-Igashi/cologne-raves/data/2026-06-fi-events.json
[
  {
    "title": "fi x Stil vor Talent",
    "venue": "fi",
    "date": "2026-06-03",
    "startTime": "23:00",
    "artists": [
      "CIOZ",
      "ELISA ELISA",
      "OLIVER KOLETZKI",
      "FABIAN KROOSS",
      "KOTOE"
    ],
    "url": "https://rausgegangen.de/events/fi-x-stil-vor-talent-1/",
    "id": "c1123575"
  },
  {
    "title": "fi GARTEN x Jonathan Kaspar -All Day Long",
    "venue": "fi",
    "date": "2026-06-04",
    "startTime": "14:00",
    "artists": ["Jonathan Kaspar"],
    "url": "https://rausgegangen.de/events/fi-garten-x-jonathan-kaspar-0/",
    "id": "73b7a826"
  },
  {
    "title": "fi x Regal & Frank Music",
    "venue": "fi",
    "date": "2026-06-06",
    "startTime": "23:00",
    "artists": [
      "ANANDA PRIORI",
      "MEDEA",
      "REGAL",
      "CLAUS CASPER",
      "JOHANNES ALBERT",
      "LINGY"
    ],
    "url": "https://rausgegangen.de/events/fi-x-regal-frank-music-0/",
    "id": "7cac312a"
  },
  {
    "title": "fi x NUOBN x Playhaus",
    "venue": "fi",
    "date": "2026-06-12",
    "startTime": "23:00",
    "artists": [
      "DI²",
      "TWO SIDED AGENCY",
      "JØRDY",
      "JOSIANE",
      "NEUTRAN",
      "RELLK0"
    ],
    "url": "https://rausgegangen.de/events/fi-x-nuobn-x-playhaus-0/",
    "id": "9ac04241"
  },
  {
    "title": "fi x Polygonia & Out Of System",
    "venue": "fi",
    "date": "2026-06-20",
    "startTime": "23:00",
    "artists": [
      "MARIAMI",
      "NULLMERIDIAN",
      "POLYGONIA",
      "BENO B.",
      "DIE JANE.",
      "GÎN BALI",
      "MELO",
      "VINESSE",
      "RINA R!OT",
      "TSAVAGE"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-polygonia-out-of-system-0/?mtm_campaign=teilen_gewinnspiel&mtm_kwd=web",
    "id": "5237a13f"
  },
  {
    "title": "fi Garten x Langer Tag x Audrey Danza & Vement & Hoove & Etage147",
    "venue": "fi",
    "date": "2026-06-27",
    "startTime": "14:00",
    "artists": [
      "Audrey Danza",
      "Vement",
      "Hoove",
      "Etage147",
      "HUGO HELTEN",
      "ISABELL & HABBEN",
      "LEON HAGEN",
      "C00LM8",
      "MF DUMM",
      "IBU400",
      "ADRI",
      "ADRIAN GASPAR",
      "OFFERGELD",
      "CLARA LUISE"
    ],
    "url": "https://rausgegangen.de/en/events/fi-garten-x-langer-tag-x-audrey-danza-vement-hoove-etage147-0/"
  }
]
