=== M-Igashi/cologne-raves/event.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "venue",
      "date",
      "title",
      "startTime"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "venue": {
        "type": "string"
      },
      "date": {
        "type": "string",
        "format": "date"
      },
      "title": {
        "type": "string"
      },
      "startTime": {
        "type": "string",
        "pattern": "^\\d{2}:\\d{2}$"
      },
      "artists": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "url": {
        "type": "string",
        "format": "uri"
      }
    },
    "additionalProperties": false
  }
}

=== M-Igashi/cologne-raves/data/2025-07-cologne-01.json
[
  {
    "id": "d751ca4c",
    "title": "fi = altshift5 w/ ANFISA LETYAGO & ICYKOF & DAS IST DAS JA",
    "venue": "fi",
    "date": "2025-07-04",
    "startTime": "23:00",
    "artists": [
      "ANFISA LETYAGO",
      "ICYKOF",
      "STIKDORN",
      "JAN OBEN",
      "PILETA B2B ANANDA PRIORI",
      "PLAY BOY JOE"
    ],
    "url": "https://www.eventbrite.com/e/fi-altshift5-w-anfisa-letyago-icykof-das-ist-das-ja-tickets-1423700670029?aff=ebdsoporgprofile&keep_tld=1"
  },
  {
    "id": "11addd38",
    "title": "fi = altshift5 w/ Dyed Soundorom & Avontuur & Chromatik",
    "venue": "fi",
    "date": "2025-07-11",
    "startTime": "23:00",
    "artists": [
      "DAVID DRÃ–GE b2b SOPHIETJE",
      "DYED SOUNDOROM",
      "SIMON BEHRENDT b2b ARNDSON",
      "CLARA LUISE",
      "JAKOB B.",
      "MARVIN RICHTER"
    ],
    "url": "https://www.eventbrite.com/e/fi-altshift5-w-dyed-soundorom-avontuur-chromatik-tickets-1408853351299?aff=ebdsoporgprofile&keep_tld=1"
  },
  {
    "id": "af8b4eff",
    "title": "fi = altshift5 w/ Marcel Dettmann & Plasma & rau.ton",
    "venue": "fi",
    "date": "2025-07-26",
    "startTime": "23:00",
    "artists": [
      "ELISEN",
      "MARCEL DETTMANN",
      "PILETA B2B EVA MO",
      "BORG BORG",
      "MAKAHAUN",
      "ROSTOM",
      "R:SELECT"
    ],
    "url": "https://www.eventbrite.com/e/fi-altshift5-w-marcel-dettmann-plasma-rauton-tickets-1437179134479?aff=ebdsoporgprofile&keep_tld=1"
  }
]

=== M-Igashi/cologne-raves/data/2025-11-cologne-10-0582d6.json
[
  {
    "id": "32c59c6d",
    "title": "fi x Elfter Elfter w/ Teki Latex & Schleuse Eins & Lafari",
    "venue": "fi",
    "date": "2025-11-11",
    "startTime": "18:00",
    "artists": [
      "AINO B2B EVOLPEED",
      "RIO SALBEI B2B RAPHAEL HANSEN",
      "SEPARAT B2B AMSL",
      "TEKI LATEX",
      "SCHLEUSE EINS",
      "LAFARI",
      "ALBERTO & ALFORNO",
      "DADDY DEE",
      "ISIS",
      "STEVE BONDE",
      "ZAHARA"
    ],
    "url": "https://www.eventbrite.com/e/fi-x-elfter-elfter-w-teki-latex-schleuse-eins-lafari-tickets-1768340156009?aff=ebdsoporgprofile&keep_tld=1"
  },
  {
    "id": "bf1d13bc",
    "title": "fi = altshift5 w/ Patrick Mason & Flinta*Tunes",
    "venue": "fi",
    "date": "2025-11-29",
    "startTime": "23:00",
    "artists": [
      "KERIMA",
      "PATRICK MASON",
      "PHILO",
      "MARUHNI",
      "MAYD",
      "SKATHI"
    ],
    "url": "https://www.eventbrite.com/e/fi-altshift5-w-patrick-mason-flintatunes-tickets-1818977313109?aff=ebdsoporgprofile&keep_tld=1"
  },
  {
    "id": "75c7733a",
    "title": "fi x [a:rpia:r] & Avontuur",
    "venue": "fi",
    "date": "2025-12-12",
    "startTime": "23:00",
    "artists": [
      "PETRE INSPIRESCU",
      "RARESH",
      "RHADOO",
      "ARNDSON B2B SIMON BEHRENDT",
      "DAVID DRÖGE",
      "SOFT FORCE",
      "SOPHIETJE"
    ],
    "url": "https://www.eventbrite.com/e/fi-x-arpiar-avontuur-tickets-1739271801779?aff=ebdsoporgprofile&keep_tld=1"
  },
  {
    "id": "38c86291",
    "title": "fi = altshift5 w/ Dax J & Hoove",
    "venue": "fi",
    "date": "2025-12-19",
    "startTime": "23:00",
    "artists": [
      "DAX J",
      "KRACKK",
      "ROBIN TASI",
      "Hoove",
      "DAAN DONK",
      "JONAS KÖKSAL",
      "JULIAN FEIERABEND",
      "THALO SANTANA"
    ],
    "url": "https://www.eventbrite.com/e/fi-altshift5-w-dax-j-hoove-tickets-1783725323459?aff=ebdsoporgprofile&keep_tld=1"
  }
]

=== M-Igashi/cologne-raves/data/2026-05-odonien-rausgegangen.json
[
  {
    "title": "Adrenaline Open Air w/ 909 Racingteam, vagabund, Satys Fyre & Schwesta2Schwesta",
    "venue": "Odonien",
    "date": "2026-05-17",
    "startTime": "14:00",
    "artists": [
      "909 Racingteam",
      "vagabund",
      "Satys Fyre",
      "Schwesta2Schwesta"
    ],
    "url": "https://adrenaline.ticket.io/xP0e6OWE/"
  },
  {
    "title": "KOMM RAVEN x Slin x Nene H x Butschi",
    "venue": "Odonien",
    "date": "2026-05-22",
    "startTime": "23:00",
    "artists": [
      "Jan Trovato",
      "C-arla",
      "Nene H",
      "Slin",
      "Kilstad",
      "bilstad",
      "Butschi",
      "Hihat",
      "Eskarlation",
      "Alias3ooo",
      "Luzia",
      "ICX",
      "Shana",
      "Evi B"
    ],
    "url": "https://rausgegangen.de/en/events/komm-raven-x-slin-x-nene-h-x-butschi-odonien-0/"
  },
  {
    "title": "WIR Schwestern 20 Years - microFESTIVAL 2026 - Day & Night",
    "venue": "Odonien",
    "date": "2026-05-24",
    "startTime": "14:00",
    "artists": [],
    "url": "https://rausgegangen.de/en/events/wir-schwestern-20-years-microfestival-2026-day-night-im-odon-0/"
  },
  {
    "title": "Praerie Frühlings-Festival",
    "venue": "Odonien",
    "date": "2026-05-30",
    "startTime": "14:00",
    "artists": [
      "Teenage Mutants",
      "Konfusia",
      "Maurice Mino",
      "Sabura",
      "Tobi Dei",
      "Aio",
      "sin:port",
      "Daniel Krau",
      "Mr. Ciao",
      "Martin Ka"
    ],
    "url": "https://rausgegangen.de/en/events/praerie-fruhlings-club-festival-im-odonien-mit-space-92-alex-0/"
  }
]

=== M-Igashi/cologne-raves/data/2025-12-01-new-ra-events.json
[
  {
    "id": "b1a40e1a",
    "venue": "Artheater",
    "date": "2025-12-05",
    "title": "HANDWERK Under Construction with Rosati, Marcel Janovsky & Boris X",
    "artists": [
      "Rosati",
      "Marcel Janovsky"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2310214"
  },
  {
    "id": "8ee21728",
    "venue": "fi",
    "date": "2025-12-05",
    "title": "fi x Feines Tier with Heimlich Knüller & nd_baumecker & Roe Deers & Keikee & Philipp Fein",
    "artists": [],
    "startTime": "23:00",
    "url": "https://ra.co/events/2313229"
  },
  {
    "id": "5bcc9403",
    "venue": "Artheater",
    "date": "2025-12-06",
    "title": "BergWacht with Bruno",
    "artists": [
      "Liho"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2314949"
  },
  {
    "id": "65631d26",
    "venue": "fi",
    "date": "2025-12-06",
    "title": "fi x Moyn Winterglow",
    "artists": [],
    "startTime": "23:00",
    "url": "https://ra.co/events/2309094"
  },
  {
    "id": "b5798477",
    "venue": "Trafic",
    "date": "2025-11-29",
    "title": "EXODIUM",
    "artists": [],
    "startTime": "23:00",
    "url": "https://ra.co/events/2310642"
  },
  {
    "id": "133365e6",
    "venue": "Garagen",
    "date": "2025-12-03",
    "title": "TECHNOLiEBE #AmMittwoch",
    "artists": [],
    "startTime": "19:00",
    "url": "https://ra.co/events/2313373"
  },
  {
    "id": "a332cc79",
    "venue": "JAKI",
    "date": "2025-12-12",
    "title": "YAYAxCHAYA",
    "artists": [
      "Gîn Bali",
      "no:elia",
      "Aaro (3)",
      "Andras_2020",
      "makahaun"
    ],
    "startTime": "23:30",
    "url": "https://ra.co/events/2307927"
  },
  {
    "id": "ca223f6f",
    "venue": "H26",
    "date": "2025-12-13",
    "title": "INHEAT. Cologne with Alberto Tolo - Danny Wabbit - Gilles Bock - Kraemer",
    "artists": [
      "Alberto Tolo",
      "Danny Wabbit",
      "Kraemer"
    ],
    "startTime": "18:00",
    "url": "https://ra.co/events/2308914"
  },
  {
    "id": "90ec4325",
    "venue": "Gewölbe",
    "date": "2025-12-13",
    "title": "Klubacht with DJ Frank, DJ Seinfeld, Sandilé",
    "artists": [
      "DJ Frank",
      "DJ Seinfeld",
      "Sandilé"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2314901"
  },
  {
    "id": "68ce7273",
    "venue": "Helios37",
    "date": "2025-12-19",
    "title": "DJ DRECKISCH WINTER TOUR x ART OF URBAN LIFE with WILDERICH, NYRA, TMR and many more",
    "artists": [
      "DJ DRECKISCH",
      "WILDERÍCH",
      "NYRA (DE)",
      "TMR (DE)",
      "TiDo",
      "nordcorreia.mp3"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2296104"
  },
  {
    "id": "53972680",
    "venue": "Bootshaus",
    "date": "2025-12-19",
    "title": "INURFASE MASSIVE - The Trinity Code",
    "artists": [
      "DitzKickz",
      "Dr Donk",
      "Lil Texas",
      "Lekkerfaces",
      "NAMARA",
      "Kili (3)",
      "Testarossa"
    ],
    "startTime": "22:30",
    "url": "https://ra.co/events/2283182"
  },
  {
    "id": "6eb67348",
    "venue": "JAKI",
    "date": "2025-12-19",
    "title": "Another Thought feat. comforter2 (live), Ultramax (live)",
    "artists": [
      "DJ Brom",
      "AMSL"
    ],
    "startTime": "21:30",
    "url": "https://ra.co/events/2299722"
  },
  {
    "id": "f064ad00",
    "venue": "Artheater",
    "date": "2025-12-19",
    "title": "ANIMADO - THE LAST DANCE (DAS FINALE BEVOR WIR AUFHÖREN)",
    "artists": [],
    "startTime": "23:00",
    "url": "https://ra.co/events/2237087"
  },
  {
    "id": "3f761769",
    "venue": "TBA - Barbarossa",
    "date": "2025-12-19",
    "title": "Beats, Bass, Barbarossa - Bassmusik in Aachen",
    "artists": [],
    "startTime": "23:00",
    "url": "https://ra.co/events/2295981"
  },
  {
    "id": "bfd9c61e",
    "venue": "Gewölbe",
    "date": "2025-12-20",
    "title": "My Dear with Kittin, Denis Stockhausen",
    "artists": [
      "Miss Kittin",
      "Denis Stockhausen"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2307071"
  },
  {
    "id": "0a653c6d",
    "venue": "King Georg",
    "date": "2025-12-20",
    "title": "Rhythmus im Blut mit Alex From Tokyo",
    "artists": [
      "Alex From Tokyo",
      "Tom Kutsche"
    ],
    "startTime": "21:00",
    "url": "https://ra.co/events/2275149"
  },
  {
    "id": "397618cc",
    "venue": "fi",
    "date": "2025-12-20",
    "title": "fi x Acid Pauli & Jonathan Kaspar & Plasma",
    "artists": [
      "Acid Pauli",
      "Jonathan Kaspar",
      "Elisen"
    ],
    "startTime": "23:00",
    "url": "https://www.eventbrite.de/e/fi-x-acid-pauli-jonathan-kaspar-plasma-tickets-1974357982875?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=cp&aff=ebdsshcopyurl"
  },
  {
    "id": "f3ae6e9d",
    "venue": "Bootshaus",
    "date": "2025-12-20",
    "title": "Bootshaus pres. AVAION - in the middle - / ZERB",
    "artists": [
      "AVAION"
    ],
    "startTime": "22:00",
    "url": "https://ra.co/events/2283195"
  },
  {
    "id": "6848f18f",
    "venue": "Schrotty",
    "date": "2025-12-20",
    "title": "Teddy Killerz ('COOKED' Tour), Tsuki, Formula, Gourski, + more - LoopLab Vol. 2",
    "artists": [
      "Teddy Killerz",
      "Formula LDN",
      "Gourski",
      "Badlokk"
    ],
    "startTime": "19:00",
    "url": "https://ra.co/events/2286305"
  },
  {
    "id": "cda78fa5",
    "venue": "Nachtigall",
    "date": "2025-12-20",
    "title": "CLUBNACHT with Aio, Pardis, Phi Φ, Juni, Bernau und Elias Paul",
    "artists": [
      "Aio",
      "Pardis"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2315134"
  },
  {
    "id": "716c7cbb",
    "venue": "Bootshaus",
    "date": "2025-12-20",
    "title": "Blacklist pres. Midnight Tyrannosaurus",
    "artists": [],
    "startTime": "23:00",
    "url": "https://ra.co/events/2308817"
  },
  {
    "id": "4ab5371d",
    "venue": "Gewölbe",
    "date": "2025-12-21",
    "title": "Research with evolpeeD, Sedaction, XDB",
    "artists": [
      "evolpeeD",
      "Sedaction",
      "XDB"
    ],
    "startTime": "14:00",
    "url": "https://ra.co/events/2314024"
  },
  {
    "id": "c208e547",
    "venue": "OFF Bar",
    "date": "2025-12-23",
    "title": "THE GET DOWN",
    "artists": [
      "DJ Funky Fresh Mike"
    ],
    "startTime": "21:00",
    "url": "https://ra.co/events/2305683"
  },
  {
    "id": "fcf19230",
    "venue": "Gewölbe",
    "date": "2025-12-24",
    "title": "Heiligabend with Shumi",
    "artists": [
      "Shumi"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2307923"
  },
  {
    "id": "19b0a4af",
    "venue": "fi",
    "date": "2025-12-27",
    "title": "fi = altshift5 w / Pan Pot & Etage147",
    "artists": [
      "ananda priori",
      "Pan-Pot"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2287702"
  },
  {
    "id": "bf9343b3",
    "venue": "Carlswerk Victoria",
    "date": "2025-12-31",
    "title": "unreal NYEve-Rave x CARV, KUKO, Somewhen,",
    "artists": [
      "CARV",
      "OMAKS",
      "Johannes Schuster",
      "KUKO",
      "Neon Graveyard",
      "NYRA (DE)",
      "Somewhen"
    ],
    "startTime": "22:00",
    "url": "https://ra.co/events/2257581"
  }
]

=== M-Igashi/cologne-raves/data/2026-05-gewoelbe-events.json
[
  {
    "title": "Gewölbe Open Air at Odonien",
    "venue": "Odonien",
    "date": "2026-05-14",
    "startTime": "14:00",
    "artists": [],
    "url": "https://gewoelbe.ticket.io/3CgheS1c/",
    "id": "e89d1207"
  },
  {
    "title": "Klubnacht",
    "venue": "Gewölbe",
    "date": "2026-05-22",
    "startTime": "23:00",
    "artists": [
      "DJ Hell",
      "Paty Vapor"
    ],
    "url": "https://gewoelbe.ticket.io/elmQzXQz/"
  },
  {
    "title": "Cologne Street Market",
    "venue": "Gewölbe",
    "date": "2026-05-23",
    "startTime": "23:00",
    "artists": [
      "c00lm8",
      "DJ Tjizza",
      "Vlizz & Yunes"
    ],
    "url": "https://gewoelbe.ticket.io/euFRDF6g/"
  },
  {
    "title": "Im Fokus",
    "venue": "Gewölbe",
    "date": "2026-05-30",
    "startTime": "23:00",
    "artists": [
      "Anna Cainelli & Denis Stockhausen",
      "Dimon & Bergen",
      "Gutkind"
    ],
    "url": "https://gewoelbe.ticket.io/hk01KFwR/",
    "id": "18d31087"
  },
  {
    "title": "Last Beat Standing",
    "venue": "Gewölbe",
    "date": "2026-06-12",
    "startTime": "23:00",
    "artists": [
      "Cinthie",
      "Meat"
    ],
    "url": "https://gewoelbe.ticket.io/CVK1x1C3/",
    "id": "49c77232"
  }
]

=== M-Igashi/cologne-raves/data/2025-08-cologne-18-fi-update-aug-6d9c7b.json
[
  {
    "id": "",
    "title": "fi x Langer Tag",
    "venue": "fi",
    "date": "2025-09-13",
    "startTime": "14:00",
    "artists": [
      "AMSL B2B LEONIE SAVALAS",
      "LENA M B2B NÂSCA",
      "RUFOUS B2B STEVE BONDE B2B ZAHARA",
      "DJ SWEET AND SOUR B2B NINI PANINI",
      "ELISEN B2B EVA MO B2B PILETA",
      "MF DUMM B2B O-LIN",
      "DJ AMP DAVID B2B SALT & PEPPER",
      "DJ PALGA B2B GIANNI B2B HIHAT",
      "NISHER B2B SKATHI"
    ],
    "url": "https://www.eventbrite.de/e/fi-x-langer-tag-tickets-1591235812149?aff=ebdsoporgprofile"
  },
  {
    "id": "1e57d56e",
    "title": "fi = altshift5 w/ Major League DJz & Barulho World & Serial Sound",
    "venue": "fi",
    "date": "2025-09-06",
    "startTime": "23:00",
    "artists": [
      "FOUDJO",
      "FRAU BEJI",
      "MAJOR LEAGUE DJZ",
      "PICCELL",
      "DJ BROM",
      "FELIX FLEER",
      "JONAS LANDWEHR"
    ],
    "url": "https://www.eventbrite.de/e/fi-altshift5-w-major-league-djz-barulho-world-serial-sound-tickets-1541511665889?aff=ebdsoporgprofile"
  },
  {
    "id": "4a38fd12",
    "title": "fi = altshift5 w/ Roman Flügel & 45 Years of Fein",
    "venue": "fi",
    "date": "2025-08-30",
    "startTime": "23:00",
    "artists": [
      "CARELESS",
      "MOTIP WHITE",
      "ROMAN FLÜGEL",
      "JOHANNES KLINGEBIEL B2B PHILIPP FEIN"
    ],
    "url": "https://www.eventbrite.de/e/fi-altshift5-w-roman-flugel-45-years-of-fein-tickets-1500402266569?aff=ebdsoporgprofile"
  }
]

=== M-Igashi/cologne-raves/data/formatted-may2025-events-deduped.json
[
  {
    "id": "",
    "title": "Ascension with MASSAGIO, Critical Error, AVO2X, Dopair, Dana Roosy",
    "venue": "Helios37",
    "date": "2025-05-02",
    "startTime": "23:00",
    "artists": [
      "MASSAGIO",
      "AVO2X",
      "Bensonius",
      "Dana Roosy"
    ],
    "url": "https://ra.co/events/2150428"
  },
  {
    "id": "",
    "title": "Fejka",
    "venue": "Yuca Club",
    "date": "2025-05-02",
    "startTime": "19:00",
    "artists": [
      "Fejká"
    ],
    "url": "https://ra.co/events/2105644"
  },
  {
    "id": "",
    "title": "Intertrax with Radial Gaze & Etane",
    "venue": "Zum Scheuen Reh",
    "date": "2025-05-02",
    "startTime": "22:00",
    "artists": [
      "Radial Gaze",
      "Etane"
    ],
    "url": "https://ra.co/events/2150171"
  },
  {
    "id": "",
    "title": "CLUBNACHT - Free Entry",
    "venue": "Nachtigall",
    "date": "2025-05-02",
    "startTime": "23:00",
    "artists": [
      "Pardis"
    ],
    "url": "https://ra.co/events/2144847"
  },
  {
    "id": "",
    "title": "EhrenKlub in Odonien #20 mit Franky-B, Isabelle Beaucamp, SANTØS uvm",
    "venue": "Odonien",
    "date": "2025-05-03",
    "startTime": "23:00",
    "artists": [
      "ALLY",
      "Dana Roosy",
      "Franky-B",
      "Isabelle Beaucamp",
      "Tzaar",
      "DOCTOR MÜCKE"
    ],
    "url": "https://ra.co/events/2147734"
  },
  {
    "id": "",
    "title": "giegling in Köln",
    "venue": "fi",
    "date": "2025-05-03",
    "startTime": "23:00",
    "artists": [
      "Leafar Legov",
      "Edward",
      "Cosmo (KR)",
      "Konstantin",
      "Yamour",
      "UNOS"
    ],
    "url": "https://ra.co/events/2126262"
  },
  {
    "id": "",
    "title": "BergWacht Ladies Night w/ SUZé, Elotanz, Klarabell, JuNi",
    "venue": "Artheater",
    "date": "2025-05-03",
    "startTime": "23:00",
    "artists": [
      "SUZé"
    ],
    "url": "https://ra.co/events/2163398"
  },
  {
    "id": "",
    "title": "Hardfusion - Cyber Meltdown",
    "venue": "Domhof",
    "date": "2025-05-03",
    "startTime": "22:00",
    "artists": [],
    "url": "https://ra.co/events/2143283"
  },
  {
    "id": "",
    "title": "SECRETRAVES // BIG SUMMER OPENING // OPEN AIR",
    "venue": "TBA - SECRET OPEN AIR",
    "date": "2025-05-03",
    "startTime": "19:00",
    "artists": [],
    "url": "https://ra.co/events/2162671"
  }
]

=== M-Igashi/cologne-raves/data/2026-07-fi-events.json
[
  {
    "title": "fi x DJ Mell G & Neue Wellen",
    "venue": "fi",
    "date": "2026-07-04",
    "startTime": "23:00",
    "artists": [
      "DJ MELL G",
      "2N1A",
      "SAVSANNAH",
      "FINE DINING",
      "VLIZZ",
      "YUNES"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-dj-mell-g-neue-wellen-0/",
    "id": "c5945f83"
  },
  {
    "title": "fi x Mama Snake & Loveselectors",
    "venue": "fi",
    "date": "2026-07-18",
    "startTime": "23:00",
    "artists": [
      "HENSO",
      "MAMA SNAKE",
      "NO:ELIA",
      "DJ KNUCKLE-BARRY",
      "JOHN WEGEHAUPT",
      "KOGI",
      "LIZZLE",
      "RAFIKI",
      "SNEAKY PETE",
      "ZINHO"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-mama-snake-loveselectors-0/",
    "id": "74332509"
  },
  {
    "title": "fi x NUOBN x Iptamenos Discos x Local Suicide",
    "venue": "fi",
    "date": "2026-07-24",
    "startTime": "23:00",
    "artists": [
      "ETANE",
      "LOCAL SUICIDE",
      "VIOLENCE MARY"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-nuobn-x-local-suicide-0/",
    "id": "5b8b038f"
  },
  {
    "title": "fi Garten x Langer Tag x Roman Flügel & Jonathan Kaspar & Barulho World uvm",
    "venue": "fi",
    "date": "2026-07-25",
    "startTime": "14:00",
    "artists": [
      "Roman Flügel",
      "Jonathan Kaspar",
      "Barulho World",
      "FrauBeji",
      "Piccell",
      "Frisotto",
      "Noah Boehm",
      "Henning Pott",
      "Yonah",
      "Kobi Föhres",
      "Arthur Uhing",
      "Lara G.",
      "Thalheimer"
    ],
    "url": "https://www.eventbrite.de/e/fi-garten-x-langer-tag-x-roman-flugel-jonathan-kaspar-barulho-world-uvm-tickets-1992487592024",
    "id": "b2a26b75"
  }
]
